/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import database.db;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fety Fatimah
 */
public class frameUangku extends javax.swing.JFrame {

    db objekku;
    public DefaultTableModel modeltabel;
    /**
     * Creates new form frameUangku
     */
    public frameUangku() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekku = new db();
        modeltabel = new DefaultTableModel();
        tableuangku.setModel(modeltabel);
        modeltabel.addColumn("ID");
        modeltabel.addColumn("TANGGAL");
        modeltabel.addColumn("KETERANGAN");
        modeltabel.addColumn("PEMASUKAN");
        modeltabel.addColumn("PENGELUARAN");
        modeltabel.addColumn("SALDO");
        tampiltableuangku();
    }
    
    public void tampiltableuangku(){
        try {
            modeltabel.getDataVector().removeAllElements();
            modeltabel.fireTableDataChanged();
            
            String sqldata = "select*from uangku order by id ASC";
            PreparedStatement querydata = objekku.konek.prepareStatement(sqldata);
            ResultSet barisdata = querydata.executeQuery();
            while(barisdata.next()){
                Object [] x = new Object[6];
                x[0] = barisdata.getString("id");
                x[1] = barisdata.getString("tanggal");
                x[2] = barisdata.getString("keterangan");
                x[3] = barisdata.getString("pemasukan");
                x[4] = barisdata.getString("pengeluaran");
                x[5] = barisdata.getString("saldo");
                
                modeltabel.addRow(x);
            } 
            barisdata.close();
            querydata.close();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtket = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpemasukan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpengeluaran = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableuangku = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id :");

        jLabel2.setText("tanggal :");

        jLabel3.setText("ket :");

        jLabel4.setText("saldo :");

        jLabel5.setText("pemasukan :");

        jLabel6.setText("pengeluaran :");

        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tableuangku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableuangku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableuangkuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableuangku);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtket, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            String sqlhapus = "delete from uangku where id=?";
            PreparedStatement x = objekku.konek.prepareStatement(sqlhapus);
            x.setString(1, txtid.getText());
            x.executeUpdate();
            tampiltableuangku();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        } catch (Exception e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            String sqlubah = "update uangku set tanggal = ?, keterangan = ?, pemasukan = ?, pengeluaran = ?, saldo = ? where id = ?";
            PreparedStatement x = objekku.konek.prepareStatement(sqlubah);
            x.setString(1, txttanggal.getText());
            x.setString(2, txtket.getText());
            x.setString(3, txtpemasukan.getText());
            x.setString(4, txtpengeluaran.getText());
            x.setString(5, txtsaldo.getText());
            x.setString(6, txtid.getText());
            x.executeUpdate();
            tampiltableuangku();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        } catch (Exception e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try {
            if (txtid.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "NPM belum di isi");
                txtid.requestFocus();//delphi setfokuc
            } else if (txttanggal.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama belum di isi");
                txttanggal.requestFocus();
            } else if (txtket.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Telepon belum di isi");
                txtket.requestFocus();
            } else if (txtpemasukan.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Telepon belum di isi");
                txtpemasukan.requestFocus();
            } else if (txtpengeluaran.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Telepon belum di isi");
                txtpengeluaran.requestFocus();
            } else if (txtsaldo.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Telepon belum di isi");
                txtsaldo.requestFocus();
            } else {
                String sqlcari = "select * from uangku where id=?";
                PreparedStatement cari = objekku.konek.prepareStatement(sqlcari);
                cari.setString(1, txtid.getText());
                ResultSet baris = cari.executeQuery();
                if (baris.next()){
                    JOptionPane.showMessageDialog(this, "ID sudah ada");
                    txttanggal.setText(baris.getString("tanggal"));
                    txtket.setText(baris.getString("keterangan"));
                    txtpemasukan.setText(baris.getString("pemasukan"));
                    txtpengeluaran.setText(baris.getString("pengeluaran"));
                    txtsaldo.setText(baris.getString("saldo"));
                } else {
                    String sqlsimpan = "insert into uangku (id, tanggal, keterangan, pemasukan, pengeluaran, saldo) value (?,?,?,?,?,?)";
                    PreparedStatement simpan = objekku.konek.prepareStatement(sqlsimpan);
                    simpan.setString(1, txtid.getText());
                    simpan.setString(2, txttanggal.getText());
                    simpan.setString(3, txtket.getText());
                    simpan.setString(4, txtpemasukan.getText());
                    simpan.setString(5, txtpengeluaran.getText());
                    simpan.setString(6, txtsaldo.getText());
                    simpan.executeUpdate();
                    tampiltableuangku();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");                    
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void tableuangkuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableuangkuMouseClicked
        // TODO add your handling code here:
        int i = tableuangku.getSelectedRow();
        String x = tableuangku.getValueAt(i, 0).toString();
        String y = tableuangku.getValueAt(i, 1).toString();
        String z = tableuangku.getValueAt(i, 2).toString();
        String a = tableuangku.getValueAt(i, 3).toString();
        String b = tableuangku.getValueAt(i, 4).toString();
        String c = tableuangku.getValueAt(i, 5).toString();
        txtid.setText(x);
        txttanggal.setText(y);
        txtket.setText(z);
        txtpemasukan.setText(a);
        txtpengeluaran.setText(b);
        txtsaldo.setText(c);
    }//GEN-LAST:event_tableuangkuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUangku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUangku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUangku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUangku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUangku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableuangku;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtket;
    private javax.swing.JTextField txtpemasukan;
    private javax.swing.JTextField txtpengeluaran;
    private javax.swing.JTextField txtsaldo;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
